"""Generate docs/TOOLS.md from the live FastMCP tool registry (mock mode)."""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server"))

from fusion_mcp.app import build_app  # noqa: E402
from fusion_mcp.config import load_config  # noqa: E402


def main():
    mcp, _client = build_app(load_config(mock=True, allow_arbitrary_code=True))
    tools = sorted(mcp._tool_manager.list_tools(), key=lambda t: t.name)

    lines = [
        "# Tool Reference / 工具参考",
        "",
        "_Auto-generated by `scripts/gen_tools_doc.py` — do not edit by hand._",
        "",
        "All distances are **millimetres (mm)**; angles are **degrees**. "
        "Bodies and sketches are referenced by **index or name**.",
        "",
        "全部尺寸单位为**毫米 (mm)**，角度为**度**。实体/草图用**索引或名称**引用。",
        "",
        "Total tools / 工具总数: **{}** (includes the gated `fusion_run_script`).".format(len(tools)),
        "",
        "| Tool | Hints | Parameters (required **bold**) | Description |",
        "|------|-------|--------------------------------|-------------|",
    ]
    for tool in tools:
        ann = tool.annotations
        hints = []
        if ann:
            if ann.readOnlyHint:
                hints.append("read-only")
            if ann.destructiveHint:
                hints.append("destructive")
            if ann.idempotentHint:
                hints.append("idempotent")
        props = tool.parameters.get("properties", {})
        required = set(tool.parameters.get("required", []))
        params = ", ".join(("**" + p + "**" if p in required else p) for p in props) or "—"
        desc = " ".join((tool.description or "").split())
        lines.append(
            "| `{}` | {} | {} | {} |".format(tool.name, ", ".join(hints) or "write", params, desc)
        )

    out = ROOT / "docs" / "TOOLS.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    sys.stderr.write("wrote {} ({} tools)\n".format(out, len(tools)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
